### ISSUE TITLE
error : git push

### ISSUE THREAD

**Issue by thayllachristine** [reprograma/github#1]
@ptonella , fiz um `git push` no meu repositório e apresentou o seguinte erro: 

```
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://github.com/thayllachristine/reprograma.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

Saberia me dizer o que seria? :dizzy_face:

**Comment by patricia-tonella** [comment]
@thayllachristine esse erro acontece quando você está tentando fazer o push mas não fez o pull primeiro (tem algum conteúdo no github que você não tem na tua máquina).
Tenta rodar um `git pull origin master`, mas pode ser que de algum conflito e você precise resolver. 
Qualquer coisa vemos amanhã e te ajudo a resolver ;)

**Comment by thayllachristine** [comment]
muito obrigada, profs 😄
